#!/usr/bin/env bash
# ============================================================================
# ⚡ Zeus Framework — Docker Entrypoint
# ============================================================================
# Bootstraps the Zeus data volume on first run, then starts hermes.
# Extends the core entrypoint with Zeus-specific setup:
#   - Installs Mnemosyne plugin
#   - Activates Zeus soul persona
#   - Syncs Zeus skills
#   - Seeds memory templates
#   - Writes Zeus config.yaml (OpenRouter + mnemosyne provider)
# ============================================================================

set -e

HERMES_HOME="${HERMES_HOME:-/opt/data}"
ZEUS_DIR="${ZEUS_DIR:-/opt/zeus}"
HERMES_INSTALL="/opt/hermes"

# ── Privilege drop (same pattern as core entrypoint) ─────────────────────────
if [ "$(id -u)" = "0" ]; then
    if [ -n "${HERMES_UID:-}" ] && [ "$HERMES_UID" != "$(id -u hermes)" ]; then
        usermod -u "$HERMES_UID" hermes
    fi
    if [ -n "${HERMES_GID:-}" ] && [ "$HERMES_GID" != "$(id -g hermes)" ]; then
        groupmod -o -g "$HERMES_GID" hermes 2>/dev/null || true
    fi
    actual_uid=$(id -u hermes)
    if [ "$(stat -c %u "$HERMES_HOME" 2>/dev/null)" != "$actual_uid" ]; then
        chown -R hermes:hermes "$HERMES_HOME" 2>/dev/null || true
    fi
    exec gosu hermes "$0" "$@"
fi

# ── Running as hermes from here ───────────────────────────────────────────────
source "${HERMES_INSTALL}/.venv/bin/activate"

# Essential directory structure
mkdir -p "$HERMES_HOME"/{cron,sessions,logs,hooks,memories,skills,skins,plans,workspace,home,plugins,memory}

# ── .env ─────────────────────────────────────────────────────────────────────
if [ ! -f "$HERMES_HOME/.env" ]; then
    cat > "$HERMES_HOME/.env" <<EOF
# Zeus Framework — auto-generated by zeus-entrypoint.sh
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-YOUR_OPENROUTER_API_KEY_HERE}
POSTGRES_HOST=${POSTGRES_HOST:-postgres}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
POSTGRES_DB=${POSTGRES_DB:-hermes_vectors}
POSTGRES_USER=${POSTGRES_USER:-hermes}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-hermes_local}
REDIS_HOST=${REDIS_HOST:-redis}
REDIS_PORT=${REDIS_PORT:-6379}
EOF
    echo "[zeus] .env bootstrapped"
else
    # Patch in the live OpenRouter key if provided via env var
    if [ -n "${OPENROUTER_API_KEY:-}" ]; then
        if grep -q "OPENROUTER_API_KEY" "$HERMES_HOME/.env"; then
            sed -i "s|^OPENROUTER_API_KEY=.*|OPENROUTER_API_KEY=$OPENROUTER_API_KEY|" "$HERMES_HOME/.env"
        else
            echo "OPENROUTER_API_KEY=$OPENROUTER_API_KEY" >> "$HERMES_HOME/.env"
        fi
    fi
fi

# ── config.yaml ──────────────────────────────────────────────────────────────
if [ ! -f "$HERMES_HOME/config.yaml" ]; then
    ZEUS_MODEL="${ZEUS_MODEL:-deepseek/deepseek-v4-pro}"
    cat > "$HERMES_HOME/config.yaml" <<EOF
# Zeus Framework — Docker config (auto-generated)
model:
  default: $ZEUS_MODEL
  provider: openrouter
  base_url: https://openrouter.ai/api/v1
  api_mode: chat_completions

fallback_model:
  provider: openrouter
  model: deepseek/deepseek-r1

toolsets:
  - hermes-cli

agent:
  max_turns: 90
  gateway_timeout: 1800
  tool_use_enforcement: auto
  verbose: false
  reasoning_effort: medium

terminal:
  backend: local
  timeout: 180
  persistent_shell: true

memory:
  memory_enabled: true
  user_profile_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375
  provider: mnemosyne
  nudge_interval: 10
  flush_min_turns: 6

approvals:
  mode: manual

security:
  redact_secrets: true
EOF
    echo "[zeus] config.yaml bootstrapped (model: $ZEUS_MODEL)"
fi

# ── Zeus soul persona ─────────────────────────────────────────────────────────
if [ ! -f "$HERMES_HOME/persona.md" ] && [ -f "$ZEUS_DIR/SOUL.md" ]; then
    cp "$ZEUS_DIR/SOUL.md" "$HERMES_HOME/persona.md"
    echo "[zeus] Soul persona activated"
fi

# ── Mnemosyne plugin ──────────────────────────────────────────────────────────
if [ -d "$ZEUS_DIR/plugins/mnemosyne" ] && [ ! -d "$HERMES_HOME/plugins/mnemosyne" ]; then
    cp -r "$ZEUS_DIR/plugins/mnemosyne" "$HERMES_HOME/plugins/"
    echo "[zeus] Mnemosyne plugin installed"
fi

# ── Memory templates ──────────────────────────────────────────────────────────
if [ -d "$ZEUS_DIR/memory" ]; then
    for f in "$ZEUS_DIR/memory"/*.example.md; do
        [ -f "$f" ] || continue
        dest="$HERMES_HOME/memory/$(basename "${f%.example.md}").md"
        [ ! -f "$dest" ] && cp "$f" "$dest"
    done
fi

# ── Skills sync ───────────────────────────────────────────────────────────────
# First sync Zeus skills into Hermes install dir so skills_sync.py sees them
if [ -d "$ZEUS_DIR/skills" ]; then
    cp -rn "$ZEUS_DIR/skills/"* "$HERMES_INSTALL/skills/" 2>/dev/null || true
fi

# Run official sync tool
if [ -f "$HERMES_INSTALL/tools/skills_sync.py" ]; then
    python3 "$HERMES_INSTALL/tools/skills_sync.py" 2>/dev/null || \
        cp -rn "$HERMES_INSTALL/skills/"* "$HERMES_HOME/skills/" 2>/dev/null || true
fi
echo "[zeus] Skills synced"

# ── Wait for dependencies ─────────────────────────────────────────────────────
wait_for() {
    local host="$1" port="$2" name="$3" retries=20
    echo "[zeus] Waiting for $name ($host:$port)..."
    for i in $(seq 1 $retries); do
        if python3 -c "import socket; s=socket.socket(); s.settimeout(1); s.connect(('$host',$port)); s.close()" 2>/dev/null; then
            echo "[zeus] $name is ready"
            return 0
        fi
        sleep 1
    done
    echo "[zeus] Warning: $name not reachable after ${retries}s — continuing anyway"
}

wait_for "${REDIS_HOST:-redis}" "${REDIS_PORT:-6379}" "Redis"
wait_for "${POSTGRES_HOST:-postgres}" "${POSTGRES_PORT:-5432}" "PostgreSQL"

echo ""
echo "  ⚡ Zeus is ready. Starting Hermes Agent..."
echo ""

exec hermes "$@"
